export const CATEGORIES = [
  "App Developer",
  "Game Developer",
  "Web Developer",
  "Software Engineer",
  "Backend Developer",
  "Frontend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "Desktop Application Developer",
  "Data Scientist",
  "Data Engineer",
  "Data Analyst",
  "Machine Learning Engineer",
  "Artificial Intelligence Engineer",
  "Big Data Engineer",
  "Deep Learning Specialist",
  "DevOps Engineer",
  "Cloud Engineer",
  "Site Reliability Engineer (SRE)",
  "Infrastructure Engineer",
  "Platform Engineer",
  "System Administrator",
  "Cybersecurity Analyst",
  "Security Engineer",
  "Penetration Tester (Ethical Hacker)",
  "Information Security Manager",
  "Network Security Engineer",
  "Network Engineer",
  "Systems Engineer",
  "Embedded Systems Developer",
  "IoT Developer",
  "Quality Assurance (QA) Engineer",
  "Automation Tester",
  "Performance Tester",
  "Manual Tester",
  "UI/UX Designer",
  "Product Designer",
  "Product Manager",
  "Interaction Designer",
  "Technical Lead",
  "Engineering Manager",
  "CTO (Chief Technology Officer)",
  "Team Lead",
  "Scrum Master",
  "Blockchain Developer",
  "Smart Contract Developer",
  "AR/VR Developer",
  "Quantum Computing Developer",
  "Database Administrator",
  "Data Architect",
  "ETL Developer",
  "Technical Writer",
  "Documentation Specialist",
  "Business Analyst",
  "Integration Specialist",
  "ERP Consultant (SAP, Oracle, etc.)",
];

export const SKILLS = [
  // Programming Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "Go",
  "Swift",
  "Kotlin",
  "PHP",
  "Rust",
  "Scala",

  // Frameworks & Libraries
  "React",
  "Angular",
  "Vue.js",
  "Next.js",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot",
  "Ruby on Rails",
  "ASP.NET",
  "TensorFlow",
  "PyTorch",

  // Databases
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Firebase",
  "OracleDB",
  "Redis",
  "Cassandra",

  // DevOps & Cloud
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Jenkins",
  "Ansible",
  "Terraform",

  // Tools & Platforms
  "Git",
  "GitHub",
  "GitLab",
  "JIRA",
  "Postman",
  "Figma",
  "Visual Studio Code",

  // Testing
  "Selenium",
  "Cypress",
  "Jest",
  "Mocha",
  "Chai",
  "JUnit",

  // Data & AI
  "Data Analysis",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Big Data",
  "Hadoop",
  "Spark",

  // Soft Skills
  "Problem Solving",
  "Communication",
  "Leadership",
  "Team Collaboration",
  "Time Management",
  "Adaptability",
];

export const AREA_OF_STUDY = [
  "Computer Science",
  "Software Engineering",
  "Information Technology",
  "Data Science",
  "Artificial Intelligence",
  "Machine Learning",
  "Cybersecurity",
  "Web Development",
  "Mobile App Development",
  "Game Development",
  "Cloud Computing",
  "Data Analytics",
  "Network Engineering",
  "Robotics",
  "Blockchain Technology",
  "Human-Computer Interaction",
  "Information Systems",
  "Database Management",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Biomedical Engineering",
  "Business Administration",
  "Economics",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Environmental Science",
  "Geographical Information Systems (GIS)",
];
